//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_user
    {
        public sys_user()
        {
            this.sys_userinrole = new HashSet<sys_userinrole>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public int Status { get; set; }
        public int CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
    
        public virtual ICollection<sys_userinrole> sys_userinrole { get; set; }
    }
}
